### PR TITLE
feat(color-palettes): removed unused color palettes

### PR DESCRIPTION
**Pull request by kumarivijeta**
## Summary

Old/unused color  palettes removed:

default
rainforest
gentletouch
savannahsunrise
crystalcavern
magenta
magentanight
braziliansunrise
tequilasunrise
eveninghorizon
energizing
cherryblossom
springgreen

## ADO Story

https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1931294

## Checklist

- [x] Used Conventional Commit messages as outlined in the contributing guide.
  - [x] Noted breaking changes (if any).
- [x] Documented/updated all props, events, slots, parts, etc with JSDoc.
  - [x] Ran the `analyze` command to update Storybook docs.
- [ ] Added/updated Stories with controls to cover all variants.
- [ ] Ran `test` locally to address any failures.
- [ ] Added/updated the Figma link for the Story's Design tab.
- [ ] Added any new component exports to the src/index.ts file
- [x] Added Migration Guide mdx docs

image

### CODE REVIEW

**Review by brian-patrick-3 — CHANGES_REQUESTED** [review]
There is a note about the deprecated colors on the docs page. Need to remove that too, but otherwise looks good.

**Comment by brian-patrick-3** [comment]
When you squash merge, include the list of removed palettes in the `BREAKING CHANGE:` commit footer.

**Comment by brian-patrick-3** [comment]
Still need to add the breaking change notes to the migration guide. I think you'll need to create that MDX file actually, copy how it was done in shidoka-appplications.

**Review by brian-patrick-3 — APPROVED** [review]

**Comment by brian-patrick-3** [comment]
You can squash merge this and include the `BREAKING CHANGES:` footer in the github textarea.

**Review by tulasigudibanda — APPROVED** [review]

**Review by jaideep08 — APPROVED** [review]

**Pull request merged**
