### PR TITLE
docs: remove old css color tokens

### PR DESCRIPTION
**Pull request by kumarivijeta**
## Summary

Updated Foundation version 1.10.0

## ADO Story or GitHub Issue Link

https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1931328

## Checklist

- [x] Used Conventional Commit messages as outlined in the contributing guide.
  - [ ] Noted breaking changes (if any).
- [ ] Documented/updated all props, events, slots, parts, etc with JSDoc.
  - [x] Ran the `analyze` command to update Storybook docs.
- [ ] Added/updated Stories with controls to cover all variants.
- [ ] Ran `test` locally to address any failures.
- [ ] Added/updated the Figma link for the Story's Design tab.
- [ ] Added any new component exports to the src/index.ts file

### CODE REVIEW

**Review by brian-patrick-3 — CHANGES_REQUESTED** [review]
You can also delete the old colors.scss file and remove it from any place it's imported.

**Review by brian-patrick-3 — CHANGES_REQUESTED** [review]
We actually do want to keep the Color Palettes page in Storybook, to show the different palettes. Sorry if I was unclear.

**Comment by kumarivijeta** [comment]
> We actually do want to keep the Color Palettes page in Storybook, to show the different palettes. Sorry if I was unclear.

> Got confused. My bad. I put it Color Palettes back :)

**Review by jaideep08 — APPROVED** [review]

**Pull request merged**
